import { readFileSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { expect, test, seedAuthSession } from './fixtures';

// The samples are generated by the independent original-XLSX XML reader.
const samplePath = process.env.FORECAST_ORIGINAL_SAMPLES;
const report = samplePath ? JSON.parse(readFileSync(samplePath, 'utf8')) : null;
test.skip(!report, 'Generate original workbook samples and set FORECAST_ORIGINAL_SAMPLES');

test('random original Excel cells match actual map colors and forward dates', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'desktop', 'Data-to-color sampling is viewport-independent; responsive map checks run separately');
  test.setTimeout(180_000);
  await seedAuthSession(page);
  const results = [];
  for (const sample of report.samples) {
    await page.goto(`/drought?mapLayer=forecast-archive&target=${sample.source_month}&horizon=${sample.horizon}`);
    const polygon = page.locator(`.nr-map-shape[data-nr-subdistrict-code="${sample.subdistrict_code}"]`);
    const expected = sample.risk_value === null ? { status: 'out-of-scope', color: null }
      : [
        { status: 'no-risk', color: 'rgb(93, 174, 121)' },
        { status: 'moderate', color: 'rgb(241, 184, 75)' },
        { status: 'high', color: 'rgb(217, 93, 89)' },
      ][sample.risk_value];
    await expect(polygon).toHaveClass(new RegExp(`is-forecast-${expected.status}(?:\\s|$)`));
    const painted = await polygon.evaluate((element) => {
      const fill = getComputedStyle(element).fill;
      const fragment = (element as SVGElement).style.fill.match(/#([^)"]+)/)?.[1];
      const pattern = fragment ? document.getElementById(fragment) : null;
      return { fill, patternBackground: pattern?.querySelector('rect')?.getAttribute('fill'),
        patternStroke: pattern?.querySelector('path')?.getAttribute('stroke'),
        status: element.getAttribute('class') };
    });
    if (expected.color) expect(painted.fill).toBe(expected.color);
    else {
      expect(painted.fill).toContain('url(');
      expect(painted.patternBackground).toBe('#e2e8e4');
      expect(painted.patternStroke).toBeTruthy();
    }
    const [year, month] = sample.target_month.split('-').map(Number);
    const labels = ['ม.ค.', 'ก.พ.', 'มี.ค.', 'เม.ย.', 'พ.ค.', 'มิ.ย.', 'ก.ค.', 'ส.ค.', 'ก.ย.', 'ต.ค.', 'พ.ย.', 'ธ.ค.'];
    await expect(page.locator('.nr-drought-workspace-context .is-target strong')).toHaveText(`${labels[month - 1]} ${year + 543}`);
    await expect(page.locator('.nr-map-legend')).toContainText('ไม่พบสัญญาณเสี่ยง');
    await expect(page.locator('.nr-map-legend')).toContainText('เสี่ยงปานกลาง');
    await expect(page.locator('.nr-map-legend')).toContainText('เสี่ยงสูง');
    await expect(page.locator('.nr-map-legend')).toContainText('นอกขอบเขตการศึกษา');
    results.push({ ...sample, actual: painted, result: 'passed' });
  }
  await writeFile(testInfo.outputPath('original-sample-browser-report.json'), JSON.stringify({ ...report,
    browser: 'Chromium', viewport: page.viewportSize(), build: 'tmp-snapshots/rev03-build',
    result: 'passed', mismatches: 0, samples: results }, null, 2));
  await page.screenshot({ path: testInfo.outputPath('original-sample-map.png'), fullPage: true });
});
